using System;

namespace Com.GitHub.ZachDeibert.ProxyConfigurer.Dns {
    public enum DnsRecordType : ushort {
        A = 1,
        NS,
        MD,
        MF,
        CNAME,
        SOA,
        MB,
        MG,
        MR,
        NULL,
        WKS,
        PTR,
        HINFO,
        MINFO,
        MX,
        TXT,
        RP,
        AFSDB,
        X25,
        ISDN,
        RT,
        NSAP,
        NSAP_PTR,
        SIG,
        KEY,
        PX,
        GPOS,
        AAAA,
        LOC,
        NXT,
        EID,
        NIMLOC,
        NB = 32,
        SRV,
        NBSTAT = 33,
        ATMA,
        NAPTR,
        KX,
        CERT,
        A6,
        DNAME,
        SINK,
        OPT,
        APL,
        DS,
        SSHFP,
        IPSECKEY,
        RRSIG,
        NSEC,
        DNSKEY,
        DHCID,
        NSEC3,
        NSEC3PARAM,
        TLSA,
        HIP = 55,
        NINFO,
        RKEY,
        TALINK,
        SPF = 99,
        UINFO,
        UID,
        GID,
        UNSPEC,
        TKEY = 249,
        TSIG,
        IXFR,
        AXFR,
        MAILB,
        MAILA,
        URI = 256,
        CAA
    }
}
